k8s_config:
- manifest_path: /manifests
  cluster_info:
    cluster_id: 85288118-9034-5661-939a-1bb53445e23d
    cluster_name: AES Smoke Tests - Yaml
- manifest_path: /manifests
  cluster_info:
    cluster_id: a995a0e9-e896-532f-94fa-b431f7db54ea
    cluster_name: AES Smoke Tests - Yaml
- manifest_path: /manifests
  cluster_info:
    cluster_id: f410c93c-a97f-5c98-b466-27a7bdfa80ea
    cluster_name: ' AES-2.3.2 GA migration'
- manifest_path: /manifests
  cluster_info:
    cluster_id: 51d1b1c8-b867-5bab-99f7-e2e10cf6e528
    cluster_name: AES-2.4.1-rc.0 Helm Install DD
- manifest_path: /manifests
  cluster_info:
    cluster_id: 091ae8d3-8552-5aaa-b4c9-cd568b367954
    cluster_name: AES 2.4.1-rc.0 Manual DD
- manifest_path: /manifests
  cluster_info:
    cluster_id: 4461dff8-ff97-5715-a9dc-c817bade1e4b
    cluster_name: AES 2.4.1-rc.0 GA Migration DD
